#!/bin/bash

###################################################################################################
# Cria um servidor web básico com uma mensagem simples - util para laboratorios Route53, NLB, etc #
# Pode ser usado no momento da criação da instancia EC2 em user data info                         #
# Este cod foi adaptado para funcionar em linux RedHat e CentOS                                   #
# Criado por Eduardo Popovici                                                                     #
###################################################################################################

sudo amazon-linux-extras install php8.0
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo '<center><h1>SITE DO EDU POPOVICI - TESTE LAB - SERVER 01:</h1></center>' > /var/www/html/index.htm
