#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
EC2ID=$(curl -s http://169.254.169.254/latest/meta-data/instances-id)
echo '<center><h1>SITE DO EDU POPOVICI - TESTE LAB - SERVER 01</h1></center>' > /var/www/html/index.txt
sed "s/EC2ID/$EC2ID/"/var/www/html/index.txt > /var/www/html/index.html
