#!/bin/bash
yum update -y
yum install httpd -y
cd /var/www/html
echo "<html><h1>Servidor-01-lab-Eduardo-Popovici</h1></html>" > index.html
systemctl start httpd.service
systemctl enable httpd.service
